name: Create and publish a Docker image to GHCR

on:
  push: {}
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image (worker)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}-worker
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          directory: worker
          dockerfile: worker/Dockerfile
          tags: ${{ github.ref_name }}
          addLatest: ${{ github.ref_name == 'main' }}

      - name: Build and push Docker image (nginx)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}-nginx
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          directory: nginx
          dockerfile: nginx/Dockerfile
          tags: ${{ github.ref_name }}
          addLatest: ${{ github.ref_name == 'main' }}
